<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>lifepunchulx</AssemblyName>
		<PackageId>lifepunchulx</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX;ADDON;DEBUG;LIFEPUNCH_PACKAGE</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<OutputPath>../../../Steam/steamapps/common/sbox/.vs/output/</OutputPath>
		<DocumentationFile>../../../Steam/steamapps/common/sbox/.vs/output/lifepunchulx.xml</DocumentationFile>
		<RootNamespace>LifePunch.DXRP.Addons.StaffMenu</RootNamespace>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
		<Using Include="Microsoft.AspNetCore.Components" />
		<Using Include="Microsoft.AspNetCore.Components.Rendering" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="../../../Steam/steamapps/common/sbox/bin/managed/Sandbox.CodeUpgrader.dll"/> 
		<Analyzer Include="../../../Steam/steamapps/common/sbox/bin/managed/Sandbox.Generator.dll"/> 
		<Reference Include="../../../Steam/steamapps/common/sbox/bin/managed/Sandbox.System.dll"/> 
		<Reference Include="../../../Steam/steamapps/common/sbox/bin/managed/Sandbox.Engine.dll"/> 
		<Reference Include="../../../Steam/steamapps/common/sbox/bin/managed/Sandbox.Filesystem.dll"/> 
		<Reference Include="../../../Steam/steamapps/common/sbox/bin/managed/Sandbox.Reflection.dll"/> 
		<Reference Include="../../../Steam/steamapps/common/sbox/bin/managed/Sandbox.Mounting.dll"/> 
		<Reference Include="../../../Steam/steamapps/common/sbox/bin/managed/Microsoft.AspNetCore.Components.dll"/> 
	</ItemGroup>

	<ItemGroup>
		<Reference Include="D:\Cavelux\lifepunch-ulx-package\.sbox\bin\package.dxura.rp.dll" />
	</ItemGroup>

</Project>
