$ErrorActionPreference = 'Stop'
$testRoot = $PSScriptRoot
$repoRoot = [IO.Path]::GetFullPath((Join-Path $testRoot '..\..'))
$sourcePath = Join-Path $repoRoot 'Code\Addons\lifepunch\lifepunchulx\observe\StaffObserveHost.cs'
$taxonomyPath = Join-Path $repoRoot 'Code\Addons\lifepunch\lifepunchulx\StaffActionTaxonomy.cs'
$source = [IO.File]::ReadAllText($sourcePath)
$sourceHash = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash
$taxonomyHash = (Get-FileHash -LiteralPath $taxonomyPath -Algorithm SHA256).Hash

function Extract-One([string]$pattern) {
    $matches = [regex]::Matches($source, $pattern)
    if ($matches.Count -ne 1) { throw "Expected one production source match: $pattern" }
    return $matches[0].Value
}

$canView = Extract-One '(?m)^\tpublic static bool CanViewObserve\(\)[^\r\n]+'
$actionLog = Extract-One '(?ms)^\tpublic static IReadOnlyList<StaffAuditEntry> StaffActionLog\(.*?;'
$activity = Extract-One '(?ms)^\tpublic static IReadOnlyList<ObserveStaffRow> StaffActivity\(\)\r?\n\t\{.*?^\t\}'
$record = Extract-One '(?ms)^public readonly record struct ObserveStaffRow\(.*?;'
$generatedRoot = Join-Path $testRoot 'generated'
[IO.Directory]::CreateDirectory($generatedRoot) | Out-Null
$utf8 = [Text.UTF8Encoding]::new($false)
$sut = "// Generated by Run.ps1 from the actual checkout; do not hand edit.`nnamespace LifePunch.DXRP.Addons.StaffMenu;`n$record`ninternal static class StaffObserveHost`n{`n$canView`n$actionLog`n$activity`n}`n"
[IO.File]::WriteAllText((Join-Path $generatedRoot 'Sut.cs'), $sut, $utf8)
[IO.File]::WriteAllBytes((Join-Path $generatedRoot 'StaffActionTaxonomy.cs'), [IO.File]::ReadAllBytes($taxonomyPath))
[IO.File]::WriteAllText((Join-Path $generatedRoot 'source-manifest.json'), (@{
    observedUtc = [DateTime]::UtcNow.ToString('o')
    source = $sourcePath
    sourceSha256 = $sourceHash
    taxonomy = $taxonomyPath
    taxonomySha256 = $taxonomyHash
    extractedMethods = @('CanViewObserve', 'StaffActionLog', 'StaffActivity')
} | ConvertTo-Json), $utf8)

& dotnet run --project (Join-Path $testRoot 'StaffActivity.Tests.csproj') --configuration Release
$result = $LASTEXITCODE
if ((Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash -ne $sourceHash -or
    (Get-FileHash -LiteralPath $taxonomyPath -Algorithm SHA256).Hash -ne $taxonomyHash) {
    throw 'Production source changed during the run; results require a fresh run.'
}
if ($result -ne 0) { throw "Staff activity regressions failed (exit $result)." }
